import {appInfo} from './Config';

/**
 * Declare all the strings here for using in throughout the app.
 */
export const Strings = {
  pleaseWait: 'Please wait...',
  noDataFound: 'No data found...',
  appUpdateDesc: `Update to the latest version to continue using ${appInfo.name}`,
  appUpdateTitle: 'Keep up-to-date',
  updateLater: 'Update Later',
  updateNow: 'Update Now',
  noInternet: 'You are offline. Please check your internet connection',
  backOnline: 'You are back online',
  noInternetConnection: 'No internet connection.',
  somethingPleaseTryAgain: 'Some error occurred please try again',
  pleaseTryAgain: 'Please try again after some time.',
  internalServer: 'Internal Server Error',
  noData: 'Not found',
  forgotPwdTitle: 'Forgot Password?',
  forgotPwdSubTitle: 'Please enter your email id to reset your \n password.',
  sendVerificationCode: 'Send Verification Code',
  email: 'Email',
  name: 'Name',
  mobileNumber: 'Mobile Number',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  signup: 'Sign up for free',
  alreadyHaveAnAccount: 'Already have an account?',
  signIn: 'SignIn',
  login: 'Login',
  createAccount: "Don't have an account?",
  verifyCode: 'Verify Code',
  ok: 'Ok',
  networkError: 'Network error',
  title: 'Democode',
  wb: 'Welcome back',
  wbMessage: 'Welcome back! Please enter your details',
  forgotPassword: 'Forgot Password?',
  continueWithGoogle: 'Continue with Google',
  signUpText: 'Sign up',
  firstName: 'First name',
  lastName: 'Last name',
  signUpSuccessfully: 'SignUp successfully',
  areYouSure: 'Are you sure you want to logout?',
  notAvailable: 'This feature is currently not available in the demo code',
};
