/**
 * Declare all the validation strings here for using in throughout the app.
 */
export const Validation = {
  appName: 'React Native template',
  validFirstNameFormat: 'Please enter valid first name',
  validLastNameFormat: 'lease enter valid last name',
  validLastName: 'Please enter valid last name',
  validEmail: 'Please enter email Id',
  validEmailFormat: 'Please enter a valid email Id',
  validPassword: 'Please enter password',
  validOldPassword: 'Please enter old password',
  validNewPassword: 'Please enter new password',
  validPasswordDetail:
    'Password must contain atleast 8 characters, 1 special character, 1 uppercase & 1 number',
  validConfirmPassword: 'Please enter confirm password',
  validConfirmPasswordLength: 'Confirm Password and Password does not match',
  validConfirmPasswordNotMatch:
    'New password and confirm password does not match',
  validConfirmNewPassword: 'Please enter confirm new password',
  forgotPwdTitle: 'Forgot Password?',
  forgotPwdSubTitle: 'Please enter your email id to reset your \n password.',
  emailId: 'Email ID',
  sendVerificationCode: 'Send Verification Code',
  FirstNameError: 'Please enter your full name',
  validFirstName: 'Please enter valid name',
  exceedNameLimit: 'Please enter less than 20 characters',
  MobileNumberError: 'Please enter mobile number',
  validMobileNumber: 'Please enter a valid mobile number',
  validMobileFormat: 'Please enter a valid mobile number',
  validState: 'Please enter state',
  validStateFormat: 'Please enter valid state',
  verifyCode: 'Verify Code',
  validOneTimePassword: 'Please enter OTP',
  validOneTimeLength: 'Please enter 4 digit valid OTP',
  validAdd: '',
  validAddFormat: '',
  validPincode: '',
  validPincodeFormat: '',
  validCity: '',
  validLocalityFormat: '',
  validCityFormat: '',
  validEmailMobileEmail: '',
  validOneTimePwd: '',
};
